/**
 * Flattened Java names → 1.12.2 registry names (minecraft-data blocksByName).
 * Unlisted modern-only blocks stay unmapped and fail on 1.12.2.
 */
import { isPreFlattenVersion } from "./constants.ts";

export const FLAT_TO_1_12: Record<string, string> = {
  "minecraft:air": "air",
  "minecraft:stone": "stone",
  "minecraft:granite": "stone",
  "minecraft:grass_block": "grass",
  "minecraft:dirt": "dirt",
  "minecraft:cobblestone": "cobblestone",
  "minecraft:oak_planks": "planks",
  "minecraft:spruce_planks": "planks",
  "minecraft:birch_planks": "planks",
  "minecraft:jungle_planks": "planks",
  "minecraft:acacia_planks": "planks",
  "minecraft:dark_oak_planks": "planks",
  "minecraft:oak_sapling": "sapling",
  "minecraft:bedrock": "bedrock",
  "minecraft:water": "water",
  "minecraft:lava": "lava",
  "minecraft:sand": "sand",
  "minecraft:gravel": "gravel",
  "minecraft:gold_ore": "gold_ore",
  "minecraft:iron_ore": "iron_ore",
  "minecraft:coal_ore": "coal_ore",
  "minecraft:oak_log": "log",
  "minecraft:spruce_log": "log",
  "minecraft:birch_log": "log",
  "minecraft:jungle_log": "log",
  "minecraft:oak_leaves": "leaves",
  "minecraft:spruce_leaves": "leaves",
  "minecraft:birch_leaves": "leaves",
  "minecraft:jungle_leaves": "leaves",
  "minecraft:glass": "glass",
  "minecraft:lapis_ore": "lapis_ore",
  "minecraft:lapis_block": "lapis_block",
  "minecraft:sandstone": "sandstone",
  "minecraft:cobweb": "web",
  "minecraft:short_grass": "tallgrass",
  "minecraft:grass": "tallgrass",
  "minecraft:obsidian": "obsidian",
  "minecraft:torch": "torch",
  "minecraft:fire": "fire",
  "minecraft:oak_stairs": "oak_stairs",
  "minecraft:chest": "chest",
  "minecraft:crafting_table": "crafting_table",
  "minecraft:furnace": "furnace",
  "minecraft:oak_door": "wooden_door",
  "minecraft:ladder": "ladder",
  "minecraft:rail": "rail",
  "minecraft:cobblestone_stairs": "stone_stairs",
  "minecraft:oak_sign": "standing_sign",
  "minecraft:lever": "lever",
  "minecraft:oak_pressure_plate": "wooden_pressure_plate",
  "minecraft:redstone_torch": "redstone_torch",
  "minecraft:stone_button": "stone_button",
  "minecraft:snow": "snow_layer",
  "minecraft:ice": "ice",
  "minecraft:snow_block": "snow",
  "minecraft:cactus": "cactus",
  "minecraft:clay": "clay",
  "minecraft:oak_fence": "fence",
  "minecraft:netherrack": "netherrack",
  "minecraft:soul_sand": "soul_sand",
  "minecraft:glowstone": "glowstone",
  "minecraft:nether_portal": "portal",
  "minecraft:carved_pumpkin": "pumpkin",
  "minecraft:jack_o_lantern": "lit_pumpkin",
  "minecraft:white_wool": "wool",
  "minecraft:orange_wool": "wool",
  "minecraft:magenta_wool": "wool",
  "minecraft:light_blue_wool": "wool",
  "minecraft:yellow_wool": "wool",
  "minecraft:lime_wool": "wool",
  "minecraft:pink_wool": "wool",
  "minecraft:gray_wool": "wool",
  "minecraft:light_gray_wool": "wool",
  "minecraft:cyan_wool": "wool",
  "minecraft:purple_wool": "wool",
  "minecraft:blue_wool": "wool",
  "minecraft:brown_wool": "wool",
  "minecraft:green_wool": "wool",
  "minecraft:red_wool": "wool",
  "minecraft:black_wool": "wool",
  "minecraft:oak_slab": "wooden_slab",
  "minecraft:bricks": "brick_block",
  "minecraft:bookshelf": "bookshelf",
  "minecraft:mossy_cobblestone": "mossy_cobblestone",
  "minecraft:oak_trapdoor": "trapdoor",
  "minecraft:iron_bars": "iron_bars",
  "minecraft:glass_pane": "glass_pane",
  "minecraft:vine": "vine",
  "minecraft:oak_fence_gate": "fence_gate",
  "minecraft:brick_stairs": "brick_stairs",
  "minecraft:stone_brick_stairs": "stone_brick_stairs",
  "minecraft:nether_bricks": "nether_brick",
  "minecraft:nether_brick_fence": "nether_brick_fence",
  "minecraft:nether_brick_stairs": "nether_brick_stairs",
  "minecraft:enchanting_table": "enchanting_table",
  "minecraft:end_portal": "end_portal",
  "minecraft:end_portal_frame": "end_portal_frame",
  "minecraft:wall_torch": "torch",
  "minecraft:redstone_wall_torch": "redstone_torch",
  "minecraft:soul_torch": "torch",
  "minecraft:soul_wall_torch": "torch",
  "minecraft:end_stone": "end_stone",
  "minecraft:redstone_lamp": "redstone_lamp",
  "minecraft:acacia_log": "log2",
  "minecraft:dark_oak_log": "log2",
  "minecraft:acacia_stairs": "acacia_stairs",
  "minecraft:dark_oak_stairs": "dark_oak_stairs",
  "minecraft:hay_block": "hay_block",
  "minecraft:hardened_clay": "hardened_clay",
  "minecraft:terracotta": "hardened_clay",
  "minecraft:packed_ice": "packed_ice",
  "minecraft:red_sandstone": "red_sandstone",
  "minecraft:repeater": "unpowered_repeater",
  "minecraft:comparator": "unpowered_comparator",
  "minecraft:redstone_wire": "redstone_wire",
  "minecraft:redstone_block": "redstone_block",
  "minecraft:hopper": "hopper",
  "minecraft:dropper": "dropper",
  "minecraft:dispenser": "dispenser",
  "minecraft:piston": "piston",
  "minecraft:sticky_piston": "sticky_piston",
  "minecraft:observer": "observer",
  "minecraft:iron_block": "iron_block",
  "minecraft:gold_block": "gold_block",
  "minecraft:diamond_block": "diamond_block",
  "minecraft:emerald_block": "emerald_block",
  "minecraft:coal_block": "coal_block",
};

export function stripNamespace(name: string): string {
  const i = name.indexOf(":");
  return i >= 0 ? name.slice(i + 1) : name;
}

export function ensureNamespace(name: string): string {
  return name.includes(":") ? name : `minecraft:${name}`;
}

export function resolveRegistryName(flatName: string, version: string): string | null {
  const full = ensureNamespace(flatName);
  if (isPreFlattenVersion(version)) {
    return FLAT_TO_1_12[full] ?? null;
  }
  return stripNamespace(full);
}
